# Generated by Django 2.2 on 2019-04-23 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='Store',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='store',
        ),
    ]
